### ISSUE TITLE
r.classicColors is undefinied after Update

### ISSUE THREAD

**Issue by fmuell2** [marcusolsson/grafana-calendar-panel#16]
I installed the recent 0.4 Version and now get the following error in the ui

![image](https://user-images.githubusercontent.com/84320356/119095919-31f1b080-ba13-11eb-9f4c-c1c7e88351f8.png)

Is there any new dependency needed?

**Comment by marcusolsson** [comment]
Sorry about that. Seems like it's been changed in recent versions of Grafana. I'll debug this and release a patch during the day.

**Comment by fmuell2** [comment]
Thanks for your fast support Marcus, reallly appreciated!

**Comment by marcusolsson** [comment]
I've published 0.4.1 where I've added a fallback palette for older Grafana versions. Could you check if that works better?

**Comment by fmuell2** [comment]
Unfortunatly its still broken. Same error as before. So i do run a too old installation? Currently we use 7.1.3

**Comment by fmuell2** [comment]
Oh i see, latest is 7.5.7. I could easily upgrade to avoid the error, but i could stay for testing on 7.1.3 if you need

**Comment by marcusolsson** [comment]
Had missed replacing all occurrences of classicColors (doh!). v0.4.2 should do it!

**Comment by fmuell2** [comment]
Can confirm. Works now for me on the old Grafana Version. Thank you!
